<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\Hash;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Traits\TransformCoordTrait;
use DB;
use Illuminate\Support\Facades\File;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;
    use TransformCoordTrait;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'login_name' => 'share_admin',
                'password' => password_hash('password', PASSWORD_ARGON2ID),
                'permission' => 0,
                'name' => 'Share',
                'provider' => 0,
                'icon_ext' => 'png',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'login_name' => 'yabashi_harimaaaa',
                'password' => password_hash('password', PASSWORD_ARGON2ID),
                'permission' => 1,
                'name' => 'はりまや',
                'provider' => 0,
                'icon_ext' => 'png',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'login_name' => 'hekiku_ramen',
                'password' => password_hash('password', PASSWORD_ARGON2ID),
                'permission' => 2,
                'name' => '中華そば 碧空',
                'provider' => 0,
                'icon_ext' => 'png',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'login_name' => 'tsuruhashi04',
                'password' => password_hash('password', PASSWORD_ARGON2ID),
                'permission' => 1,
                'name' => 'ツル☆ハシ',
                'provider' => 0,
                'icon_ext' => 'png',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'login_name' => 'yanagi_yuki',
                'password' => password_hash('password', PASSWORD_ARGON2ID),
                'permission' => 1,
                'name' => '柳 勇樹',
                'provider' => 0,
                'icon_ext' => 'png',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'login_name' => 'test_user',
                'password' => password_hash('password123', PASSWORD_ARGON2ID),
                'permission' => 1,
                'name' => 'テスト太郎',
                'provider' => 0,
                'icon_ext' => 'png',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // 二要素認証テスト用
        DB::table('users')->insert([
            [
                'login_name' => '2fa_user',
                'password' => password_hash('password123', PASSWORD_ARGON2ID),
                'permission' => 1,
                'name' => '二要素 次郎',
                'provider' => 0,
                'icon_ext' => 'png',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'totp_secret' => '12345678', //この項目があるので分ける
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('spots')->insert([
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 0,
                'name' => 'chimney',
                'lng' => $this->encodeLng(133.676274),
                'lat' => $this->encodeLat(33.583968),
                'postal_code' => 7820024,
                'addr_city' => 39212,
                'addr_detail' => '土佐山田町神通寺３４６－２',
                'description' =>
                    '人気絵本「パンどろぼう」のモチーフになったとされる、土佐山田のパン屋。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => 'ごめん・なはり線',
                'lng' => $this->encodeLng(133.906497),
                'lat' => $this->encodeLat(33.504458),
                'postal_code' => 7820010,
                'addr_city' => 39203,
                'addr_detail' => '東浜２９４',
                'description' =>
                    '南国市後免町と安芸郡奈半利町を結ぶ、2002年に開業した第三セクター路線。JR四国の路線と接続している。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => 'とさでん交通（電車）',
                'lng' => $this->encodeLng(133.54293),
                'lat' => $this->encodeLat(33.559524),
                'postal_code' => 7800833,
                'addr_city' => 39201,
                'addr_detail' => '南はりまや町１丁目',
                'description' =>
                    '南国市・高知市・吾川郡いの町を結ぶ路面電車。高知県唯一の電車でもある。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => 'はりまや橋',
                'lng' => $this->encodeLng(133.542639),
                'lat' => $this->encodeLat(33.559944),
                'postal_code' => 7800822,
                'addr_city' => 39201,
                'addr_detail' => 'はりまや町１丁目',
                'description' =>
                    '高知市の中心部にある橋。日本三大がっかり名所の一つとして知られる。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 0,
                'name' => 'ひばり食堂',
                'lng' => $this->encodeLng(133.663903),
                'lat' => $this->encodeLat(33.764472),
                'postal_code' => 7890312,
                'addr_city' => 39344,
                'addr_detail' => '高須２２６',
                'description' =>
                    'デカ盛りの聖地として知られる食堂。メディアに取り上げられることも多く、全国的に有名。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 1,
                'name' => 'ひろめ市場',
                'lng' => $this->encodeLng(133.535937),
                'lat' => $this->encodeLat(33.560116),
                'postal_code' => 7800841,
                'addr_city' => 39201,
                'addr_detail' => '帯屋町２丁目３－１',
                'description' =>
                    '飲食店や土産物店が軒を連ねる市場。観光スポットとしても、地元民の飲みの場としても人気。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 1,
                'name' => 'べんべん',
                'lng' => $this->encodeLng(133.648148),
                'lat' => $this->encodeLat(33.565033),
                'postal_code' => 7830005,
                'addr_city' => 39204,
                'addr_detail' => '大そね乙１０２４',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 1,
                'name' => 'カフェ・ド・梵',
                'lng' => $this->encodeLng(133.539161),
                'lat' => $this->encodeLat(33.560795),
                'postal_code' => 7800841,
                'addr_city' => 39201,
                'addr_detail' => '帯屋町１丁目１４−３３',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '一条神社',
                'lng' => $this->encodeLng(132.93424),
                'lat' => $this->encodeLat(32.993625),
                'postal_code' => 7870001,
                'addr_city' => 39210,
                'addr_detail' => '中村本町１丁目１１',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '中村城',
                'lng' => $this->encodeLng(132.927481),
                'lat' => $this->encodeLat(32.996896),
                'postal_code' => 7870005,
                'addr_city' => 39210,
                'addr_detail' => '中村',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '中村駅',
                'lng' => $this->encodeLng(132.94405),
                'lat' => $this->encodeLat(32.984347),
                'postal_code' => 7870014,
                'addr_city' => 39210,
                'addr_detail' => '駅前町７',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '介良事件UFO発見場所',
                'lng' => $this->encodeLng(133.596917),
                'lat' => $this->encodeLat(33.554778),
                'postal_code' => 7815106,
                'addr_city' => 39201,
                'addr_detail' => '介良乙',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '伊尾木洞',
                'lng' => $this->encodeLng(133.933232),
                'lat' => $this->encodeLat(33.491279),
                'postal_code' => 7840045,
                'addr_city' => 39203,
                'addr_detail' => '伊尾木１１７',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '伊尾木駅',
                'lng' => $this->encodeLng(133.929105),
                'lat' => $this->encodeLat(33.49098),
                'postal_code' => 7840045,
                'addr_city' => 39203,
                'addr_detail' => '伊尾木',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '伊野駅',
                'lng' => $this->encodeLng(133.430126),
                'lat' => $this->encodeLat(33.547502),
                'postal_code' => 7812105,
                'addr_city' => 39386,
                'addr_detail' => '新町',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '伊野駅前電停',
                'lng' => $this->encodeLng(133.410687),
                'lat' => $this->encodeLat(33.548444),
                'postal_code' => 7812110,
                'addr_city' => 39386,
                'addr_detail' => '新町',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '佐田沈下橋',
                'lng' => $this->encodeLng(132.885529),
                'lat' => $this->encodeLat(33.015388),
                'postal_code' => 7871106,
                'addr_city' => 39210,
                'addr_detail' => '佐田',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '八王寺宮',
                'lng' => $this->encodeLng(133.878653),
                'lat' => $this->encodeLat(33.698712),
                'postal_code' => 7814401,
                'addr_city' => 39212,
                'addr_detail' => '物部町大栃１６４４',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '勝間沈下橋',
                'lng' => $this->encodeLng(132.818943),
                'lat' => $this->encodeLat(33.05399),
                'postal_code' => 7871226,
                'addr_city' => 39210,
                'addr_detail' => '鵜ノ江',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '十二所神社',
                'lng' => $this->encodeLng(133.914423),
                'lat' => $this->encodeLat(33.71319),
                'postal_code' => 7814404,
                'addr_city' => 39212,
                'addr_detail' => '物部町小浜３０７',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '四国カルスト',
                'lng' => $this->encodeLng(132.939796),
                'lat' => $this->encodeLat(33.471975),
                'postal_code' => 7850601,
                'addr_city' => 39405,
                'addr_detail' => '永野',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '土佐国衙跡',
                'lng' => $this->encodeLng(133.648733),
                'lat' => $this->encodeLat(33.599765),
                'postal_code' => 7830054,
                'addr_city' => 39204,
                'addr_detail' => '比江７０３',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 1,
                'name' => '土佐壺屋',
                'lng' => $this->encodeLng(133.745165),
                'lat' => $this->encodeLat(33.603392),
                'postal_code' => 7820005,
                'addr_city' => 39212,
                'addr_detail' => '土佐山田町逆川１４２９',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '土佐山田駅',
                'lng' => $this->encodeLng(133.685008),
                'lat' => $this->encodeLat(33.607107),
                'postal_code' => 7820031,
                'addr_city' => 39212,
                'addr_detail' => '土佐山田町東本町１丁目５',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '土佐日記御崎の泊碑',
                'lng' => $this->encodeLng(133.945313),
                'lat' => $this->encodeLat(33.35462),
                'postal_code' => 7817101,
                'addr_city' => 39202,
                'addr_detail' => '室戸岬町',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '土佐清水',
                'lng' => $this->encodeLng(132.893762),
                'lat' => $this->encodeLat(32.828648),
                'postal_code' => 7870300,
                'addr_city' => 39209,
                'addr_detail' => '',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '地球33番地モニュメント',
                'lng' => $this->encodeLng(133.556651),
                'lat' => $this->encodeLat(33.562624),
                'postal_code' => 7810074,
                'addr_city' => 39209,
                'addr_detail' => '弥生町',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '大日寺',
                'lng' => $this->encodeLng(133.705054),
                'lat' => $this->encodeLat(33.577751),
                'postal_code' => 7815222,
                'addr_city' => 39211,
                'addr_detail' => '野市町母代寺４７６',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '奈半利駅',
                'lng' => $this->encodeLng(134.015487),
                'lat' => $this->encodeLat(33.425015),
                'postal_code' => 7816402,
                'addr_city' => 39302,
                'addr_detail' => '乙',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '寅さん地蔵',
                'lng' => $this->encodeLng(133.932012),
                'lat' => $this->encodeLat(33.491327),
                'postal_code' => 7840045,
                'addr_city' => 39203,
                'addr_detail' => '伊尾木１６９−６',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '小松神社',
                'lng' => $this->encodeLng(133.971462),
                'lat' => $this->encodeLat(33.740289),
                'postal_code' => 7814642,
                'addr_city' => 39212,
                'addr_detail' => '物部町別役',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '帯屋町商店街',
                'lng' => $this->encodeLng(133.537674),
                'lat' => $this->encodeLat(33.560802),
                'postal_code' => 7800841,
                'addr_city' => 39201,
                'addr_detail' => '帯屋町１丁目９',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '後免',
                'lng' => $this->encodeLng(133.646004),
                'lat' => $this->encodeLat(33.575791),
                'postal_code' => 7830011,
                'addr_city' => 39204,
                'addr_detail' => '後免町',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '後免駅',
                'lng' => $this->encodeLng(133.645348),
                'lat' => $this->encodeLat(33.579231),
                'postal_code' => 7830002,
                'addr_city' => 39204,
                'addr_detail' => '駅前町２丁目４',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 0,
                'name' => '得月楼',
                'lng' => $this->encodeLng(133.544223),
                'lat' => $this->encodeLat(33.559077),
                'postal_code' => 7800833,
                'addr_city' => 39201,
                'addr_detail' => '南はりまや町１丁目１７−３',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '戸板島橋',
                'lng' => $this->encodeLng(133.694599),
                'lat' => $this->encodeLat(33.590164),
                'postal_code' => 7815223,
                'addr_city' => 39211,
                'addr_detail' => '野市町西佐古',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '手結港可動橋',
                'lng' => $this->encodeLng(133.756593),
                'lat' => $this->encodeLat(33.528739),
                'postal_code' => 7815621,
                'addr_city' => 39211,
                'addr_detail' => '夜須町手結２９８−１９',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '新改駅',
                'lng' => $this->encodeLng(133.695696),
                'lat' => $this->encodeLat(33.649569),
                'postal_code' => 7820063,
                'addr_city' => 39212,
                'addr_detail' => '土佐山田町東川',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '日曜市',
                'lng' => $this->encodeLng(133.695696),
                'lat' => $this->encodeLat(33.649569),
                'postal_code' => 7800842,
                'addr_city' => 39201,
                'addr_detail' => '追手筋',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '朝日出山の大杉',
                'lng' => $this->encodeLng(134.069654),
                'lat' => $this->encodeLat(33.526993),
                'postal_code' => 7816201,
                'addr_city' => 39306,
                'addr_detail' => '馬路',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '杉の大スギ',
                'lng' => $this->encodeLng(133.662568),
                'lat' => $this->encodeLat(33.754904),
                'postal_code' => 7890311,
                'addr_city' => 39344,
                'addr_detail' => '杉７９４',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '松尾港',
                'lng' => $this->encodeLng(132.984717),
                'lat' => $this->encodeLat(32.732116),
                'postal_code' => 7870316,
                'addr_city' => 39209,
                'addr_detail' => '松尾１７１−２',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '桂浜',
                'lng' => $this->encodeLng(133.57487),
                'lat' => $this->encodeLat(33.497454),
                'postal_code' => 7810262,
                'addr_city' => 39201,
                'addr_detail' => '浦戸６',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '森家住宅',
                'lng' => $this->encodeLng(134.02378),
                'lat' => $this->encodeLat(33.427076),
                'postal_code' => 7816402,
                'addr_city' => 39302,
                'addr_detail' => '乙２５９５',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '沢田マンション',
                'lng' => $this->encodeLng(133.553051),
                'lat' => $this->encodeLat(33.579463),
                'postal_code' => 7810011,
                'addr_city' => 39201,
                'addr_detail' => '薊野北町１丁目１０−３',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 0,
                'name' => '活魚 漁ま',
                'lng' => $this->encodeLng(133.564565),
                'lat' => $this->encodeLat(33.564949),
                'postal_code' => 7810087,
                'addr_city' => 39201,
                'addr_detail' => '南久保１−２',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '浅尾沈下橋',
                'lng' => $this->encodeLng(133.25581),
                'lat' => $this->encodeLat(33.567648),
                'postal_code' => 7811325,
                'addr_city' => 39403,
                'addr_detail' => '浅尾',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 4,
                'name' => '湖畔遊',
                'lng' => $this->encodeLng(133.771852),
                'lat' => $this->encodeLat(33.652938),
                'postal_code' => 7814224,
                'addr_city' => 39212,
                'addr_detail' => '香北町有瀬１００',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '石立山登山道入口',
                'lng' => $this->encodeLng(134.030636),
                'lat' => $this->encodeLat(33.772464),
                'postal_code' => 7814644,
                'addr_city' => 39212,
                'addr_detail' => '物部町別府',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '神峯寺',
                'lng' => $this->encodeLng(133.974774),
                'lat' => $this->encodeLat(33.467634),
                'postal_code' => 7816422,
                'addr_city' => 39304,
                'addr_detail' => '唐浜２５９４',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '竜串',
                'lng' => $this->encodeLng(133.576579),
                'lat' => $this->encodeLat(33.546544),
                'postal_code' => 7870452,
                'addr_city' => 39209,
                'addr_detail' => '竜串',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '竹林寺',
                'lng' => $this->encodeLng(133.576579),
                'lat' => $this->encodeLat(33.546544),
                'postal_code' => 7818125,
                'addr_city' => 39201,
                'addr_detail' => '五台山３５７７',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '若井駅',
                'lng' => $this->encodeLng(133.10598),
                'lat' => $this->encodeLat(33.188074),
                'postal_code' => 7860068,
                'addr_city' => 39412,
                'addr_detail' => '若井',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '若宮八幡宮',
                'lng' => $this->encodeLng(133.543908),
                'lat' => $this->encodeLat(33.494666),
                'postal_code' => 7810270,
                'addr_city' => 39201,
                'addr_detail' => '長浜６６００',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 3,
                'name' => '西島園芸団地',
                'lng' => $this->encodeLng(133.639529),
                'lat' => $this->encodeLat(33.592502),
                'postal_code' => 730023,
                'addr_city' => 39204,
                'addr_detail' => '廿枝６００',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '足摺岬',
                'lng' => $this->encodeLng(133.008628),
                'lat' => $this->encodeLat(32.736847),
                'postal_code' => 7870315,
                'addr_city' => 39209,
                'addr_detail' => '足摺岬',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '金剛福寺',
                'lng' => $this->encodeLng(133.018681),
                'lat' => $this->encodeLat(32.725584),
                'postal_code' => 7870315,
                'addr_city' => 39209,
                'addr_detail' => '足摺岬２１４−１',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '香美市立やなせたかし記念館',
                'lng' => $this->encodeLng(133.78375),
                'lat' => $this->encodeLat(33.647694),
                'postal_code' => 7814212,
                'addr_city' => 39212,
                'addr_detail' => '香北町美良布１２２４−２',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '香美市立大栃診療所',
                'lng' => $this->encodeLng(133.874143),
                'lat' => $this->encodeLat(33.696658),
                'postal_code' => 7814401,
                'addr_city' => 39212,
                'addr_detail' => '物部町大栃８９８−１',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '高知城',
                'lng' => $this->encodeLng(133.531484),
                'lat' => $this->encodeLat(33.560812),
                'postal_code' => 7800850,
                'addr_city' => 39201,
                'addr_detail' => '丸ノ内１丁目２−１',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '高知空港',
                'lng' => $this->encodeLng(133.67407),
                'lat' => $this->encodeLat(33.547609),
                'postal_code' => 7830096,
                'addr_city' => 39204,
                'addr_detail' => '久枝乙５８',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '高知駅',
                'lng' => $this->encodeLng(133.543645),
                'lat' => $this->encodeLat(33.567227),
                'postal_code' => 7800061,
                'addr_city' => 39201,
                'addr_detail' => '栄田町',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '高知県立牧野植物園',
                'lng' => $this->encodeLng(133.579183),
                'lat' => $this->encodeLat(33.547908),
                'postal_code' => 7818125,
                'addr_city' => 39201,
                'addr_detail' => '五台山４２００−６',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '高知県立高知小津高等学校',
                'lng' => $this->encodeLng(133.526115),
                'lat' => $this->encodeLat(33.563875),
                'postal_code' => 7800916,
                'addr_city' => 39201,
                'addr_detail' => '城北町１−１４',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '高知県立高知追手前高等学校',
                'lng' => $this->encodeLng(133.536556),
                'lat' => $this->encodeLat(33.561596),
                'postal_code' => 7800842,
                'addr_city' => 39201,
                'addr_detail' => '追手筋２丁目２−１０',
                'description' => '',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 3,
                'name' => '龍河洞',
                'lng' => $this->encodeLng(133.74259),
                'lat' => $this->encodeLat(33.603392),
                'postal_code' => 7820005,
                'addr_city' => 39212,
                'addr_detail' => '土佐山田町逆川１４２４',
                'description' => '',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('keywords')->insert([
            [
                'spot_id' => 1,
                'keyword' => 'パンどろぼう',
            ],
            [
                'spot_id' => 2,
                'keyword' => 'ラスト・ソング・フォー・ユー',
            ],
            [
                'spot_id' => 3,
                'keyword' => 'ラスト・ソング・フォー・ユー',
            ],
            [
                'spot_id' => 3,
                'keyword' => '海がきこえる',
            ],
            [
                'spot_id' => 4,
                'keyword' => 'The Harimaya Bridge はりまや橋',
            ],
            [
                'spot_id' => 4,
                'keyword' => 'たいようのマキバオー',
            ],
            [
                'spot_id' => 4,
                'keyword' => 'クッキンアイドル アイ！マイ！まいん！',
            ],
            [
                'spot_id' => 4,
                'keyword' => 'ゴリパラ見聞録',
            ],
            [
                'spot_id' => 4,
                'keyword' => '南国土佐を後にして',
            ],
            [
                'spot_id' => 4,
                'keyword' => '海がきこえる',
            ],
            [
                'spot_id' => 4,
                'keyword' =>
                    '特捜戦隊デカレンジャー 20th ファイヤーボール・ブースター',
            ],
            [
                'spot_id' => 5,
                'keyword' => '所さんの学校では教えてくれないそこんトコロ！',
            ],
            [
                'spot_id' => 6,
                'keyword' => 'おへんろ。',
            ],
            [
                'spot_id' => 6,
                'keyword' => '東海オンエア',
            ],
            [
                'spot_id' => 7,
                'keyword' => '旅するSnow Man / 完全版 Travel 3',
            ],
            [
                'spot_id' => 8,
                'keyword' => '東海オンエア',
            ],
            [
                'spot_id' => 9,
                'keyword' => 'おとぎ奉り',
            ],
            [
                'spot_id' => 10,
                'keyword' => 'おとぎ奉り',
            ],
            [
                'spot_id' => 11,
                'keyword' => 'おとぎ奉り',
            ],
            [
                'spot_id' => 11,
                'keyword' => '遅咲きのヒマワリ〜ボクの人生、リニューアル〜',
            ],
            [
                'spot_id' => 12,
                'keyword' => 'Miracle☆Summer',
            ],
            [
                'spot_id' => 12,
                'keyword' => 'ボクは好奇心のかたまり',
            ],
            [
                'spot_id' => 12,
                'keyword' => 'ラジオアドベンチャー奇界遺産',
            ],
            [
                'spot_id' => 13,
                'keyword' => 'らんまん',
            ],
            [
                'spot_id' => 14,
                'keyword' => '男はつらいよ',
            ],
            [
                'spot_id' => 15,
                'keyword' => '竜とそばかすの姫',
            ],
            [
                'spot_id' => 16,
                'keyword' => '県庁おもてなし課',
            ],
            [
                'spot_id' => 17,
                'keyword' => 'クッキンアイドル アイ！マイ！まいん！',
            ],
            [
                'spot_id' => 17,
                'keyword' => '宇宙人のあいつ',
            ],
            [
                'spot_id' => 17,
                'keyword' => '遅咲きのヒマワリ〜ボクの人生、リニューアル〜',
            ],
            [
                'spot_id' => 18,
                'keyword' => 'ものべの',
            ],
            [
                'spot_id' => 19,
                'keyword' => '釣りバカ日誌14 お遍路大パニック!',
            ],
            [
                'spot_id' => 20,
                'keyword' => 'ものべの',
            ],
            [
                'spot_id' => 21,
                'keyword' => 'らんまん',
            ],
            [
                'spot_id' => 21,
                'keyword' => '宇宙人のあいつ',
            ],
            [
                'spot_id' => 22,
                'keyword' => '土佐日記',
            ],
            [
                'spot_id' => 23,
                'keyword' => '東海オンエア',
            ],
            [
                'spot_id' => 24,
                'keyword' => 'ものべの',
            ],
            [
                'spot_id' => 25,
                'keyword' => '土佐日記',
            ],
            [
                'spot_id' => 26,
                'keyword' => '夏が来たから',
            ],
            [
                'spot_id' => 27,
                'keyword' => 'ゴリパラ見聞録',
            ],
            [
                'spot_id' => 28,
                'keyword' => 'そふてにっ',
            ],
            [
                'spot_id' => 29,
                'keyword' => 'おへんろ。',
            ],
            [
                'spot_id' => 30,
                'keyword' => '寅さん地蔵',
            ],
            [
                'spot_id' => 31,
                'keyword' => 'ものべの',
            ],
            [
                'spot_id' => 32,
                'keyword' => '君が踊る、夏',
            ],
            [
                'spot_id' => 32,
                'keyword' => '宇宙人のあいつ',
            ],
            [
                'spot_id' => 32,
                'keyword' => '竜とそばかすの姫',
            ],
            [
                'spot_id' => 33,
                'keyword' => 'おからの華',
            ],
            [
                'spot_id' => 34,
                'keyword' => 'あんぱん',
            ],
            [
                'spot_id' => 35,
                'keyword' => '陽暉楼',
            ],
            [
                'spot_id' => 35,
                'keyword' => '鬼龍院花子の生涯',
            ],
            [
                'spot_id' => 36,
                'keyword' => '旅するSnow Man / 完全版 Travel 3',
            ],
            [
                'spot_id' => 37,
                'keyword' => 'ダイハツ工業 CM「そびえ立つ道」篇',
            ],
            [
                'spot_id' => 37,
                'keyword' => 'ピタゴラスイッチ',
            ],
            [
                'spot_id' => 37,
                'keyword' => '県庁おもてなし課',
            ],
            [
                'spot_id' => 38,
                'keyword' =>
                    'ナゼそこ？ 1日の利用客ゼロ人!?秘境駅 山奥の行き止まりで秘境人発見',
            ],
            [
                'spot_id' => 39,
                'keyword' =>
                    '特捜戦隊デカレンジャー 20th ファイヤーボール・ブースター',
            ],
            [
                'spot_id' => 39,
                'keyword' => '県庁おもてなし課',
            ],
            [
                'spot_id' => 40,
                'keyword' => 'Miracle☆Summer',
            ],
            [
                'spot_id' => 41,
                'keyword' => '美空ひばり',
            ],
            [
                'spot_id' => 42,
                'keyword' => '釣りバカ日誌14 お遍路大パニック!',
            ],
            [
                'spot_id' => 43,
                'keyword' => 'いごっそ魂',
            ],
            [
                'spot_id' => 43,
                'keyword' => 'クッキンアイドル アイ！マイ！まいん！',
            ],
            [
                'spot_id' => 43,
                'keyword' => 'ゴリパラ見聞録',
            ],
            [
                'spot_id' => 43,
                'keyword' => 'トラック野郎・故郷特急便',
            ],
            [
                'spot_id' => 43,
                'keyword' => '君が踊る、夏',
            ],
            [
                'spot_id' => 43,
                'keyword' => '悲報伝',
            ],
            [
                'spot_id' => 43,
                'keyword' => '桂浜',
            ],
            [
                'spot_id' => 43,
                'keyword' => '海がきこえる',
            ],
            [
                'spot_id' => 43,
                'keyword' =>
                    '特捜戦隊デカレンジャー 20th ファイヤーボール・ブースター',
            ],
            [
                'spot_id' => 43,
                'keyword' => '県庁おもてなし課',
            ],
            [
                'spot_id' => 44,
                'keyword' => 'Miracle☆Summer',
            ],
            [
                'spot_id' => 45,
                'keyword' => '小春日記。',
            ],
            [
                'spot_id' => 45,
                'keyword' => '住人十色',
            ],
            [
                'spot_id' => 45,
                'keyword' => '別冊アサ（秘）ジャーナル',
            ],
            [
                'spot_id' => 45,
                'keyword' => '探偵!ナイトスクープ',
            ],
            [
                'spot_id' => 45,
                'keyword' => '週刊プレイボーイ 2005年9月6日号',
            ],
            [
                'spot_id' => 45,
                'keyword' => '初恋電車',
            ],
            [
                'spot_id' => 45,
                'keyword' => '東海オンエア',
            ],
            [
                'spot_id' => 47,
                'keyword' => '君が踊る、夏',
            ],
            [
                'spot_id' => 47,
                'keyword' => '県庁おもてなし課',
            ],
            [
                'spot_id' => 47,
                'keyword' => '竜とそばかすの姫',
            ],
            [
                'spot_id' => 48,
                'keyword' => '旅するSnow Man / 完全版 Travel 3',
            ],
            [
                'spot_id' => 49,
                'keyword' => 'ものべの',
            ],
            [
                'spot_id' => 50,
                'keyword' => 'おへんろ。',
            ],
            [
                'spot_id' => 51,
                'keyword' => '釣りバカ日誌14 お遍路大パニック!',
            ],
            [
                'spot_id' => 52,
                'keyword' => 'おへんろ。',
            ],
            [
                'spot_id' => 53,
                'keyword' => 'CD聴こうよ。',
            ],
            [
                'spot_id' => 54,
                'keyword' => "ざつ旅-That's Journey- 第6巻",
            ],
            [
                'spot_id' => 55,
                'keyword' => '旅するSnow Man / 完全版 Travel 3',
            ],
            [
                'spot_id' => 56,
                'keyword' => 'あしずり岬',
            ],
            [
                'spot_id' => 56,
                'keyword' => '旅の重さ',
            ],
            [
                'spot_id' => 56,
                'keyword' => '足摺岬',
            ],
            [
                'spot_id' => 57,
                'keyword' => '釣りバカ日誌14 お遍路大パニック!',
            ],
            [
                'spot_id' => 58,
                'keyword' => 'あんぱん',
            ],
            [
                'spot_id' => 58,
                'keyword' => 'それいけ！アンパンマン',
            ],
            [
                'spot_id' => 59,
                'keyword' => 'ものべの',
            ],
            [
                'spot_id' => 60,
                'keyword' => 'クッキンアイドル アイ！マイ！まいん！',
            ],
            [
                'spot_id' => 60,
                'keyword' => 'ゴリパラ見聞録',
            ],
            [
                'spot_id' => 60,
                'keyword' => '南鎌倉高校女子自転車部 第3話',
            ],
            [
                'spot_id' => 60,
                'keyword' => '君が踊る、夏',
            ],
            [
                'spot_id' => 60,
                'keyword' => '海がきこえる',
            ],
            [
                'spot_id' => 60,
                'keyword' =>
                    '特捜戦隊デカレンジャー 20th ファイヤーボール・ブースター',
            ],
            [
                'spot_id' => 61,
                'keyword' => '奇跡体験!アンビリバボー 2022年5月26日',
            ],
            [
                'spot_id' => 61,
                'keyword' => '戦後重大事件の新事実2017〜事件発生から〇年〜',
            ],
            [
                'spot_id' => 61,
                'keyword' => '海がきこえる',
            ],
            [
                'spot_id' => 61,
                'keyword' =>
                    '生死を分けたその瞬間 体感！奇跡のリアルタイム 2015年3月18日',
            ],
            [
                'spot_id' => 62,
                'keyword' => 'ボクは五才',
            ],
            [
                'spot_id' => 62,
                'keyword' => '君が踊る、夏',
            ],
            [
                'spot_id' => 62,
                'keyword' => '竜とそばかすの姫',
            ],
            [
                'spot_id' => 62,
                'keyword' => '遅咲きのヒマワリ〜ボクの人生、リニューアル〜',
            ],
            [
                'spot_id' => 63,
                'keyword' => 'おへんろ。',
            ],
            [
                'spot_id' => 63,
                'keyword' => 'らんまん',
            ],
            [
                'spot_id' => 63,
                'keyword' =>
                    '特捜戦隊デカレンジャー 20th ファイヤーボール・ブースター',
            ],
            [
                'spot_id' => 64,
                'keyword' => '政宗くんのリベンジ',
            ],
            [
                'spot_id' => 65,
                'keyword' => '海がきこえる',
            ],
            [
                'spot_id' => 66,
                'keyword' => 'ものべの',
            ],
            [
                'spot_id' => 66,
                'keyword' => '東海オンエア',
            ],
        ]);
        DB::table('reviews')->insert([
            [
                'spot_id' => 2,
                'user_id' => 1,
                'rate' => 5,
                'comment' => '車窓から海が見えて最高でした！',
                'views' => 1,
                'ip_addr' => '192.0.2.11',
                'port' => 49211,
                'user_agent' =>
                    'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Mobile Safari/537.36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('coupons')->insert([
            [
                'spot_id' => 1,
                'name' => 'テストクーポン（実際には使用できません）',
                'cond_spot_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('user_coupons')->insert([
            [
                'coupon_id' => 1,
                'user_id' => 2,
                'key' => $this->randKey(),
                'is_used' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'coupon_id' => 1,
                'user_id' => 5,
                'key' => $this->randKey(),
                'is_used' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('stamps')->insert([
            [
                'spot_id' => 2,
                'user_id' => 2,
                'ip_addr' => '192.0.2.21',
                'port' => 49231,
                'user_agent' =>
                    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:146.0) Gecko/20100101 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 2,
                'user_id' => 5,
                'ip_addr' => '192.0.2.22',
                'port' => 49231,
                'user_agent' =>
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 Edg/143.0.0.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('queries')->insert([
            [
                'user_id' => 2,
                'query' => 'この間にある観光スポットを推薦して',
                'from_spot_id' => 2,
                'to_spot_id' => 6,
                'ip_addr' => '192.0.2.31',
                'port' => 49231,
                'user_agent' =>
                    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:146.0) Gecko/20100101 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'query' => '「ものべの」の聖地はどこ？',
                'from_spot_id' => null,
                'to_spot_id' => null,
                'ip_addr' => '192.0.2.32',
                'port' => 49232,
                'user_agent' =>
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:146.0) Gecko/20100101 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('photos')->insert([
            [
                'user_id' => 4,
                'lng' => $this->encodeLng(133.685047),
                'lat' => $this->encodeLat(33.607133),
                'img_ext' => 'jpg',
                'comment' =>
                    'ついに香美市に到着！あのゲームにも出てきた場所、土佐山田駅だ！',
                'ip_addr' => '192.0.2.41',
                'port' => 49241,
                'user_agent' =>
                    'Mozilla/5.0 (Android 15; Mobile; rv:146.0) Gecko/146.0 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('api_keys')->insert([
            [
                'user_id' => 3,
                'name' => 'テスト用',
                'key' => hash(
                    'sha3-512',
                    'R9AnJFbw34/CWEQhwBVzDC4BGiAfM6IigWoU5pKm9L7y3zh6mzKEB32KjcyhPdq.d6hNo6+Iykh0EOVHQ/Wyp',
                    true,
                ),
                'ip_addr' => '192.0.2.51',
                'port' => 49251,
                'user_agent' =>
                    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:146.0) Gecko/20100101 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        File::copyDirectory(__DIR__ . '/files', storage_path('app/public'));
    }
    private function randKey()
    {
        return rand(0, PHP_INT_MAX);
    }
}
