<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\Hash;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Traits\TransformCoordTrait;
use DB;
use Illuminate\Support\Facades\File;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;
    use TransformCoordTrait;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'login_name' => 'share_admin',
                'password' => password_hash('password', PASSWORD_ARGON2ID),
                'permission' => 0,
                'name' => 'Share',
                'provider' => 0,
                'icon_ext' => 'JPG',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'login_name' => 'yabashi_harimaaaa',
                'password' => password_hash('password', PASSWORD_ARGON2ID),
                'permission' => 1,
                'name' => 'はりまや',
                'provider' => 0,
                'icon_ext' => 'jpg',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'login_name' => 'hekiku_ramen',
                'password' => password_hash('password', PASSWORD_ARGON2ID),
                'permission' => 2,
                'name' => '中華そば 碧空',
                'provider' => 0,
                'icon_ext' => 'jpg',
                'num_plan_std' => 1,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'login_name' => 'tsuruhashi04',
                'password' => password_hash('password', PASSWORD_ARGON2ID),
                'permission' => 1,
                'name' => 'ツル☆ハシ',
                'provider' => 0,
                'icon_ext' => 'jpg',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'login_name' => 'yanagi_yuki',
                'password' => password_hash('password', PASSWORD_ARGON2ID),
                'permission' => 1,
                'name' => '柳 勇樹',
                'provider' => 0,
                'icon_ext' => 'jpg',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'login_name' => 'test_user',
                'password' => password_hash('password123', PASSWORD_ARGON2ID),
                'permission' => 1,
                'name' => 'テスト太郎',
                'provider' => 0,
                'icon_ext' => 'jpg',
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // 二要素認証テスト用
        DB::table('users')->insert([
            [
                'login_name' => '2fa_user',
                'password' => password_hash('password123', PASSWORD_ARGON2ID),
                'permission' => 1,
                'name' => '二要素 次郎',
                'provider' => 0,
                'icon_ext' => null,
                'num_plan_std' => 0,
                'num_plan_prm' => 0,
                'totp_secret' => '12345678', //この項目があるので分ける
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // ---------------------------------------------------------
        // 2. 観光スポットデータの作成
        // ---------------------------------------------------------
        DB::table('spots')->insert([
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 0,
                'name' => 'chimney',
                'lng' => $this->encodeLng(133.676274),
                'lat' => $this->encodeLat(33.583968),
                'postal_code' => 7820024,
                'addr_city' => 39212,
                'addr_detail' => '土佐山田町神通寺３４６－２',
                'description' =>
                    '人気絵本「パンどろぼう」のモチーフになったとされる、土佐山田のパン屋。',
                'img_ext' => 'JPG',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => 'ごめん・なはり線',
                'lng' => $this->encodeLng(133.906497),
                'lat' => $this->encodeLat(33.504458),
                'postal_code' => 7820010,
                'addr_city' => 39203,
                'addr_detail' => '東浜２９４',
                'description' =>
                    '南国市後免町と安芸郡奈半利町を結ぶ、2002年に開業した第三セクター路線。JR四国の路線と接続している。オープンデッキ車両からの眺めが人気。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => 'とさでん交通（電車）',
                'lng' => $this->encodeLng(133.54293),
                'lat' => $this->encodeLat(33.559524),
                'postal_code' => 7800833,
                'addr_city' => 39201,
                'addr_detail' => '南はりまや町１丁目',
                'description' =>
                    '南国市・高知市・吾川郡いの町を結ぶ路面電車。現役最古の路面電車として知られ、高知市民の重要な足となっている。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => 'はりまや橋',
                'lng' => $this->encodeLng(133.542639),
                'lat' => $this->encodeLat(33.559944),
                'postal_code' => 7800822,
                'addr_city' => 39201,
                'addr_detail' => 'はりまや町１丁目',
                'description' =>
                    '高知市の中心部にある橋。「日本三大がっかり名所」の一つとして逆に有名だが、夜のライトアップや周辺の公園は風情がある。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 0,
                'name' => 'ひばり食堂',
                'lng' => $this->encodeLng(133.663903),
                'lat' => $this->encodeLat(33.764472),
                'postal_code' => 7890312,
                'addr_city' => 39344,
                'addr_detail' => '高須２２６',
                'description' =>
                    'デカ盛りの聖地として知られる大豊町の食堂。カツ丼のボリュームが凄まじく、県内外から多くのファンが訪れる。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 1,
                'name' => 'ひろめ市場',
                'lng' => $this->encodeLng(133.535937),
                'lat' => $this->encodeLat(33.560116),
                'postal_code' => 7800841,
                'addr_city' => 39201,
                'addr_detail' => '帯屋町２丁目３－１',
                'description' =>
                    '飲食店や土産物店が軒を連ねる巨大屋台村。カツオのたたきをつまみに昼から酒を飲む地元民と観光客で常に賑わっている。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 1,
                'name' => 'べんべん',
                'lng' => $this->encodeLng(133.648148),
                'lat' => $this->encodeLat(33.565033),
                'postal_code' => 7830005,
                'addr_city' => 39204,
                'addr_detail' => '大そね乙１０２４',
                'description' =>
                    '高知県内で展開するお弁当チェーン店。ボリューム満点のお弁当がリーズナブルに楽しめる、学生や地元民の味方。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 1,
                'name' => 'カフェ・ド・梵',
                'lng' => $this->encodeLng(133.539161),
                'lat' => $this->encodeLat(33.560795),
                'postal_code' => 7800841,
                'addr_city' => 39201,
                'addr_detail' => '帯屋町１丁目１４−３３',
                'description' =>
                    '帯屋町商店街にある老舗の喫茶店。レトロな雰囲気の中で落ち着いた時間を過ごせる。シフォンケーキなどのスイーツも人気。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '一条神社',
                'lng' => $this->encodeLng(132.93424),
                'lat' => $this->encodeLat(32.993625),
                'postal_code' => 7870001,
                'addr_city' => 39210,
                'addr_detail' => '中村本町１丁目１１',
                'description' =>
                    '土佐一条氏の祖、一条教房公を祀る神社。「土佐の小京都」と呼ばれる中村の象徴的な場所であり、市民に親しまれている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '中村城',
                'lng' => $this->encodeLng(132.929342),
                'lat' => $this->encodeLat(32.996936),
                'postal_code' => 7870005,
                'addr_city' => 39210,
                'addr_detail' => '中村',
                'description' =>
                    '四万十市を見下ろす為松公園内にある城跡。模擬天守があり、四万十川や中村の街並みを一望できる桜の名所でもある。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '中村駅',
                'lng' => $this->encodeLng(132.94405),
                'lat' => $this->encodeLat(32.984347),
                'postal_code' => 7870014,
                'addr_city' => 39210,
                'addr_detail' => '駅前町７',
                'description' =>
                    '土佐くろしお鉄道の中村線と宿毛線を繋ぐ駅。四万十川観光の玄関口であり、グッドデザイン賞を受賞したリノベーション後のモダンな駅舎も必見。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '介良事件UFO発見場所',
                'lng' => $this->encodeLng(133.596917),
                'lat' => $this->encodeLat(33.554778),
                'postal_code' => 7815106,
                'addr_city' => 39201,
                'addr_detail' => '介良乙',
                'description' =>
                    '1972年、地元中学生が小型UFOを捕獲したとされる「介良事件」の現場。オカルトファンの間では伝説的な聖地となっている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '伊尾木洞',
                'lng' => $this->encodeLng(133.933232),
                'lat' => $this->encodeLat(33.491279),
                'postal_code' => 7840045,
                'addr_city' => 39203,
                'addr_detail' => '伊尾木１１７',
                'description' =>
                    '波の浸食によりできた天然の洞窟。壁面にシダ植物が群生しており、ジブリ映画のような神秘的な世界が広がっている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '伊尾木駅',
                'lng' => $this->encodeLng(133.929105),
                'lat' => $this->encodeLat(33.49098),
                'postal_code' => 7840045,
                'addr_city' => 39203,
                'addr_detail' => '伊尾木',
                'description' =>
                    'ごめん・なはり線の駅。伊尾木洞への最寄り駅である。駅のキャラクターとして、やなせたかし氏デザインの「いおき トラオ君」がいる。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '伊野駅',
                'lng' => $this->encodeLng(133.430126),
                'lat' => $this->encodeLat(33.547502),
                'postal_code' => 7812105,
                'addr_city' => 39386,
                'addr_detail' => '新町',
                'description' =>
                    'JR土讃線の駅。映画「竜とそばかすの姫」の舞台モデルの一つとしても知られ、聖地巡礼に訪れるファンも多い。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '伊野駅前電停',
                'lng' => $this->encodeLng(133.428433),
                'lat' => $this->encodeLat(33.54845),
                'postal_code' => 7812110,
                'addr_city' => 39386,
                'addr_detail' => '新町',
                'description' =>
                    'とさでん交通伊野線の終点駅。レトロな路面電車が発着し、すぐ近くには紙の博物館などがある。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '佐田沈下橋',
                'lng' => $this->encodeLng(132.885529),
                'lat' => $this->encodeLat(33.015388),
                'postal_code' => 7871106,
                'addr_city' => 39210,
                'addr_detail' => '佐田',
                'description' =>
                    '四万十川最下流に位置する、最も長い沈下橋。アクセスが良く、シーズンには多くの観光客で賑わう人気のフォトスポット。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '八王寺宮',
                'lng' => $this->encodeLng(133.878653),
                'lat' => $this->encodeLat(33.698712),
                'postal_code' => 7814401,
                'addr_city' => 39212,
                'addr_detail' => '物部町大栃１６４４',
                'description' =>
                    '香美市物部町にある神社。秋の紅葉や、地域の伝統的なお祭りで知られる静謐なスポット。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '勝間沈下橋',
                'lng' => $this->encodeLng(132.818943),
                'lat' => $this->encodeLat(33.05399),
                'postal_code' => 7871226,
                'addr_city' => 39210,
                'addr_detail' => '鵜ノ江',
                'description' =>
                    '橋脚が3本ある珍しい沈下橋。映画「釣りバカ日誌14」のロケ地としても有名で、釣りファンにも親しまれている。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '十二所神社',
                'lng' => $this->encodeLng(133.916497),
                'lat' => $this->encodeLat(33.71319),
                'postal_code' => 7814404,
                'addr_city' => 39212,
                'addr_detail' => '物部町小浜３１０',
                'description' =>
                    'ゲーム「ものべの」の聖地としてファンに知られる神社。百合の大樹があり、神秘的な雰囲気が漂う。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '四国カルスト',
                'lng' => $this->encodeLng(132.939796),
                'lat' => $this->encodeLat(33.471975),
                'postal_code' => 7850601,
                'addr_city' => 39405,
                'addr_detail' => '永野',
                'description' =>
                    '日本三大カルストの一つ。白い石灰岩が点在する高原風景は「日本のスイス」とも呼ばれ、絶景ドライブやキャンプが楽しめる。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '土佐国衙跡',
                'lng' => $this->encodeLng(133.648733),
                'lat' => $this->encodeLat(33.599765),
                'postal_code' => 7830054,
                'addr_city' => 39204,
                'addr_detail' => '比江７０３',
                'description' =>
                    '平安時代の土佐国の役所跡。南国市にあり、紀貫之が国司として赴任した場所として歴史ファンに知られる。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 1,
                'name' => '土佐壺屋',
                'lng' => $this->encodeLng(133.745165),
                'lat' => $this->encodeLat(33.603392),
                'postal_code' => 7820005,
                'addr_city' => 39212,
                'addr_detail' => '土佐山田町逆川１４２９',
                'description' =>
                    '龍河洞の入り口近くにある刃物店や土産物店。伝統的な土佐打刃物などを扱っている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '土佐山田駅',
                'lng' => $this->encodeLng(133.685008),
                'lat' => $this->encodeLat(33.607107),
                'postal_code' => 7820031,
                'addr_city' => 39212,
                'addr_detail' => '土佐山田町東本町１丁目５',
                'description' =>
                    '香美市の玄関口となるJR土讃線の駅。アンパンマンミュージアムや龍河洞へのバスが発着する観光拠点。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '土佐日記御崎の泊碑',
                'lng' => $this->encodeLng(134.180312),
                'lat' => $this->encodeLat(33.24996),
                'postal_code' => 7817101,
                'addr_city' => 39202,
                'addr_detail' => '室戸岬町',
                'description' =>
                    '紀貫之が「土佐日記」に記した室戸岬周辺の停泊地を記念した石碑。文学と歴史のロマンを感じさせるスポット。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '土佐清水',
                'lng' => $this->encodeLng(132.893762),
                'lat' => $this->encodeLat(32.828648),
                'postal_code' => 7870300,
                'addr_city' => 39209,
                'addr_detail' => '',
                'description' =>
                    '四国最南端の市。足摺岬や清水サバで有名。ジョン万次郎の出身地としても知られる。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '地球33番地モニュメント',
                'lng' => $this->encodeLng(133.556651),
                'lat' => $this->encodeLat(33.562624),
                'postal_code' => 7810074,
                'addr_city' => 39209,
                'addr_detail' => '弥生町',
                'description' =>
                    '東経133度33分33秒、北緯33度33分33秒という「3」が12個並ぶ世界的にも珍しい地点。川の中にモニュメントがある。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '大日寺',
                'lng' => $this->encodeLng(133.705054),
                'lat' => $this->encodeLat(33.577751),
                'postal_code' => 7815222,
                'addr_city' => 39211,
                'addr_detail' => '野市町母代寺４７６',
                'description' =>
                    '四国八十八箇所霊場の第28番札所。奥の院にある「爪彫り薬師」は首から上の病にご利益があると言われている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '奈半利駅',
                'lng' => $this->encodeLng(134.01813),
                'lat' => $this->encodeLat(33.42484),
                'postal_code' => 7816402,
                'addr_city' => 39302,
                'addr_detail' => '乙',
                'description' =>
                    'ごめん・なはり線の終着駅。高架駅からは太平洋が一望できる。駅舎内には物産館もあり便利。駅のキャラクターとして、やなせたかし氏デザインの「なは りこちゃん」がいる。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '寅さん地蔵',
                'lng' => $this->encodeLng(133.932012),
                'lat' => $this->encodeLat(33.491327),
                'postal_code' => 7840045,
                'addr_city' => 39203,
                'addr_detail' => '伊尾木１６９−６',
                'description' =>
                    '映画「男はつらいよ」のロケ地となる予定だった伊尾木に、寅さんを演じる渥美清さんの急逝をしのんで建立された地蔵。伊尾木洞の近くにあり、ファンが訪れるスポットとなっている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '小松神社',
                'lng' => $this->encodeLng(133.97503),
                'lat' => $this->encodeLat(33.74016),
                'postal_code' => 7814642,
                'addr_city' => 39212,
                'addr_detail' => '物部町別役',
                'description' =>
                    '物部町の山奥に鎮座する神社。平家の落人伝説が残り、静寂に包まれた境内は厳かな雰囲気が漂う。国の重要無形民俗文化財となっている「いざなぎ流」が伝承されている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '帯屋町商店街',
                'lng' => $this->encodeLng(133.540249),
                'lat' => $this->encodeLat(33.560802),
                'postal_code' => 7800841,
                'addr_city' => 39201,
                'addr_detail' => '帯屋町１丁目９',
                'description' =>
                    '高知市最大のアーケード商店街。よさこい祭りの競演場にもなり、ショッピングやグルメの中心地。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '後免',
                'lng' => $this->encodeLng(133.646004),
                'lat' => $this->encodeLat(33.575791),
                'postal_code' => 7830011,
                'addr_city' => 39204,
                'addr_detail' => '後免町',
                'description' =>
                    '南国市の中心エリア。「ごめん」という地名から、謝罪の聖地（？）としてユニークな町おこしも行われている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '後免駅',
                'lng' => $this->encodeLng(133.645348),
                'lat' => $this->encodeLat(33.579231),
                'postal_code' => 7830002,
                'addr_city' => 39204,
                'addr_detail' => '駅前町２丁目４',
                'description' =>
                    'JR土讃線とごめん・なはり線が接続する交通の要衝。やなせたかし氏デザインの「ごめん えきお君」がいる。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 0,
                'name' => '得月楼',
                'lng' => $this->encodeLng(133.544223),
                'lat' => $this->encodeLat(33.559077),
                'postal_code' => 7800833,
                'addr_city' => 39201,
                'addr_detail' => '南はりまや町１丁目１７−３',
                'description' =>
                    '明治創業の老舗料亭。小説・映画「鬼龍院花子の生涯」の舞台としても有名で、伝統的な土佐料理を味わえる。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '戸板島橋',
                'lng' => $this->encodeLng(133.694599),
                'lat' => $this->encodeLat(33.590164),
                'postal_code' => 7815223,
                'addr_city' => 39211,
                'addr_detail' => '野市町西佐古',
                'description' =>
                    '物部川にかかるコンクリート製の沈下橋。のどかな風景の中にあり、サイクリングや散歩コースとして親しまれている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '手結港可動橋',
                'lng' => $this->encodeLng(133.756593),
                'lat' => $this->encodeLat(33.528739),
                'postal_code' => 7815621,
                'addr_city' => 39211,
                'addr_detail' => '夜須町手結２９８−１９',
                'description' =>
                    '船の出入りのために道路が垂直に跳ね上がる可動橋。橋が立っている姿は圧巻で、CMロケ地などにも使われる。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '新改駅',
                'lng' => $this->encodeLng(133.695696),
                'lat' => $this->encodeLat(33.649569),
                'postal_code' => 7820063,
                'addr_city' => 39212,
                'addr_detail' => '土佐山田町東川',
                'description' =>
                    '山奥にあるJR土讃線の秘境駅。スイッチバック式の駅として鉄道ファンに有名で、静寂に包まれた独特の雰囲気がある。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '日曜市',
                'lng' => $this->encodeLng(133.537661),
                'lat' => $this->encodeLat(33.561445),
                'postal_code' => 7800842,
                'addr_city' => 39201,
                'addr_detail' => '追手筋',
                'description' =>
                    '毎週日曜日に高知城追手門から続く通りで開催される、日本最大級の街路市。新鮮な野菜や芋天などの食べ歩きが楽しめる。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '朝日出山の大杉',
                'lng' => $this->encodeLng(134.069654),
                'lat' => $this->encodeLat(33.526993),
                'postal_code' => 7816201,
                'addr_city' => 39306,
                'addr_detail' => '馬路',
                'description' =>
                    '馬路村にある巨大な杉の木。地域の人々に信仰されてきた巨木で、自然の力強さを感じられるパワースポット。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '杉の大スギ',
                'lng' => $this->encodeLng(133.662568),
                'lat' => $this->encodeLat(33.754904),
                'postal_code' => 7890311,
                'addr_city' => 39344,
                'addr_detail' => '杉７９４',
                'description' =>
                    '日本一の大杉として知られる国の特別天然記念物。若き日の美空ひばりが願掛けをしたことでも有名。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '松尾港',
                'lng' => $this->encodeLng(132.984717),
                'lat' => $this->encodeLat(32.732116),
                'postal_code' => 7870316,
                'addr_city' => 39209,
                'addr_detail' => '松尾１７１−２',
                'description' =>
                    '土佐清水市にある港。アコウの巨木などの自然景観が近くにあり、静かな漁港の風情を楽しめる。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '桂浜',
                'lng' => $this->encodeLng(133.57487),
                'lat' => $this->encodeLat(33.497454),
                'postal_code' => 7810262,
                'addr_city' => 39201,
                'addr_detail' => '浦戸６',
                'description' =>
                    '高知を代表する景勝地。弓状の砂浜と松林、そして太平洋を見つめる坂本龍馬像があり、月の名所としても知られる。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '森家住宅',
                'lng' => $this->encodeLng(134.02378),
                'lat' => $this->encodeLat(33.427076),
                'postal_code' => 7816402,
                'addr_city' => 39302,
                'addr_detail' => '乙２５９５',
                'description' =>
                    '奈半利町にある土佐漆喰と水切り瓦が特徴的な古民家。国の登録有形文化財であり、往時の繁栄を伝えている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '沢田マンション',
                'lng' => $this->encodeLng(133.553051),
                'lat' => $this->encodeLat(33.579463),
                'postal_code' => 7810011,
                'addr_city' => 39201,
                'addr_detail' => '薊野北町１丁目１０−３',
                'description' =>
                    '「日本の九龍城」とも呼ばれる、夫婦二人で建設したセルフビルドの巨大マンション。建築ファンに人気のスポット。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 0,
                'name' => '活魚 漁ま',
                'lng' => $this->encodeLng(133.564565),
                'lat' => $this->encodeLat(33.564949),
                'postal_code' => 7810087,
                'addr_city' => 39201,
                'addr_detail' => '南久保１−２',
                'description' =>
                    'いけすから揚げたばかりの新鮮な魚料理が楽しめる人気店。カツオのたたきや豪快な定食が評判。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '浅尾沈下橋',
                'lng' => $this->encodeLng(133.25581),
                'lat' => $this->encodeLat(33.567648),
                'postal_code' => 7811325,
                'addr_city' => 39403,
                'addr_detail' => '浅尾',
                'description' =>
                    '仁淀川にかかる沈下橋。映画「竜とそばかすの姫」の舞台モデルとなり、周囲の山々と清流のコントラストが美しい。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 4,
                'name' => '湖畔遊',
                'lng' => $this->encodeLng(133.771852),
                'lat' => $this->encodeLat(33.652938),
                'postal_code' => 7814224,
                'addr_city' => 39212,
                'addr_detail' => '香北町有瀬１００',
                'description' =>
                    '物部川の湖畔にある温泉カフェ。絶景を眺めながら入る温泉や、こだわりの食事が楽しめる癒やしの空間。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '石立山登山道入口',
                'lng' => $this->encodeLng(134.030419),
                'lat' => $this->encodeLat(33.773166),
                'postal_code' => 7814644,
                'addr_city' => 39212,
                'addr_detail' => '物部町別府',
                'description' =>
                    '四国屈指の険しい山、石立山への登山口。紅葉の美しさで知られる別府峡谷の近くにあり、ここにある橋は紅葉狩りのスポットにもなっている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '神峯寺',
                'lng' => $this->encodeLng(133.974774),
                'lat' => $this->encodeLat(33.467634),
                'postal_code' => 7816422,
                'addr_city' => 39304,
                'addr_detail' => '唐浜２５９４',
                'description' =>
                    '四国八十八箇所霊場の第27番札所。「真っ縦（まったて）」と呼ばれる急勾配の参道がある、遍路転がしの難所。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '竜串',
                'lng' => $this->encodeLng(132.864324),
                'lat' => $this->encodeLat(32.787565),
                'postal_code' => 7870452,
                'addr_city' => 39209,
                'addr_detail' => '竜串',
                'description' =>
                    '砂岩が風や波に侵食されてできた奇岩が連なる景勝地。地質学的にも貴重で、異世界のような風景が広がる。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '竹林寺',
                'lng' => $this->encodeLng(133.576579),
                'lat' => $this->encodeLat(33.546544),
                'postal_code' => 7818125,
                'addr_city' => 39201,
                'addr_detail' => '五台山３５７７',
                'description' =>
                    '四国八十八箇所霊場の第31番札所。美しい庭園や五重塔があり、「土佐の文殊さん」として学業成就の信仰も厚い。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '若井駅',
                'lng' => $this->encodeLng(133.10598),
                'lat' => $this->encodeLat(33.188074),
                'postal_code' => 7860068,
                'addr_city' => 39412,
                'addr_detail' => '若井',
                'description' =>
                    'JR予土線と土佐くろしお鉄道中村線の分岐点となる駅。四万十川沿いを走る列車の旅の拠点となる小さな駅。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 255,
                'name' => '若宮八幡宮',
                'lng' => $this->encodeLng(133.543908),
                'lat' => $this->encodeLat(33.494666),
                'postal_code' => 7810270,
                'addr_city' => 39201,
                'addr_detail' => '長浜６６００',
                'description' =>
                    '長宗我部元親が初陣の際に戦勝祈願をしたことで知られる神社。必勝祈願のパワースポット。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 3,
                'name' => '西島園芸団地',
                'lng' => $this->encodeLng(133.639529),
                'lat' => $this->encodeLat(33.592502),
                'postal_code' => 730023,
                'addr_city' => 39204,
                'addr_detail' => '廿枝６００',
                'description' =>
                    '一年中メロンやスイカが楽しめる観光農園。ブーゲンビリアが咲き誇るハウス内で食べるフルーツやパンケーキが人気。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '足摺岬',
                'lng' => $this->encodeLng(133.020333),
                'lat' => $this->encodeLat(32.724028),
                'postal_code' => 7870315,
                'addr_city' => 39209,
                'addr_detail' => '足摺岬',
                'description' =>
                    '四国最南端の岬。断崖絶壁に立つ白亜の灯台と太平洋の大パノラマは圧巻。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '金剛福寺',
                'lng' => $this->encodeLng(133.018681),
                'lat' => $this->encodeLat(32.725584),
                'postal_code' => 7870315,
                'addr_city' => 39209,
                'addr_detail' => '足摺岬２１４−１',
                'description' =>
                    '足摺岬にある四国八十八箇所霊場の第38番札所。広大な境内と美しい庭園を持ち、弘法大師ゆかりの地。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '香美市立やなせたかし記念館',
                'lng' => $this->encodeLng(133.78375),
                'lat' => $this->encodeLat(33.647694),
                'postal_code' => 7814212,
                'addr_city' => 39212,
                'addr_detail' => '香北町美良布１２２４−２',
                'description' =>
                    'アンパンマンの作者、やなせたかし氏の故郷にある美術館。通称アンパンマンミュージアムとして、親子連れに大人気。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '香美市立大栃診療所',
                'lng' => $this->encodeLng(133.874143),
                'lat' => $this->encodeLat(33.696658),
                'postal_code' => 7814401,
                'addr_city' => 39212,
                'addr_detail' => '物部町大栃８９８−１',
                'description' =>
                    'ゲーム「ものべの」の聖地巡礼スポットの一つとして知られる場所。物部川のほとりにある。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '高知城',
                'lng' => $this->encodeLng(133.531484),
                'lat' => $this->encodeLat(33.560812),
                'postal_code' => 7800850,
                'addr_city' => 39201,
                'addr_detail' => '丸ノ内１丁目２−１',
                'description' =>
                    '現存十二天守の一つ。追手門と天守閣が両方現存している珍しい城で、高知市のシンボル。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '高知空港',
                'lng' => $this->encodeLng(133.67407),
                'lat' => $this->encodeLat(33.547609),
                'postal_code' => 7830096,
                'addr_city' => 39204,
                'addr_detail' => '久枝乙５８',
                'description' =>
                    '愛称は「高知龍馬空港」。高知の空の玄関口であり、到着ロビーでは坂本龍馬像が出迎えてくれる。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 6,
                'name' => '高知駅',
                'lng' => $this->encodeLng(133.543645),
                'lat' => $this->encodeLat(33.567227),
                'postal_code' => 7800061,
                'addr_city' => 39201,
                'addr_detail' => '栄田町',
                'description' =>
                    '「くじらドーム」と呼ばれる大屋根が特徴的な駅。駅前には幕末の三志士像が立ち並ぶ。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '高知県立牧野植物園',
                'lng' => $this->encodeLng(133.579183),
                'lat' => $this->encodeLat(33.547908),
                'postal_code' => 7818125,
                'addr_city' => 39201,
                'addr_detail' => '五台山４２００−６',
                'description' =>
                    '植物学者・牧野富太郎博士を顕彰する植物園。3000種類以上の植物が彩る美しい庭園や温室は必見。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '高知県立高知小津高等学校',
                'lng' => $this->encodeLng(133.526115),
                'lat' => $this->encodeLat(33.563875),
                'postal_code' => 7800916,
                'addr_city' => 39201,
                'addr_detail' => '城北町１−１４',
                'description' =>
                    '漫画・アニメ「政宗くんのリベンジ」の舞台モデルとなった高校。聖地巡礼に訪れるファンもいる。（見学はマナーを守って）',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => '高知県立高知追手前高等学校',
                'lng' => $this->encodeLng(133.536556),
                'lat' => $this->encodeLat(33.561596),
                'postal_code' => 7800842,
                'addr_city' => 39201,
                'addr_detail' => '追手筋２丁目２－１０',
                'description' =>
                    '時計台のある歴史的な校舎が特徴。日曜市の通りに面しており、高知の風景の一部となっている。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 3,
                'name' => '龍河洞',
                'lng' => $this->encodeLng(133.745178),
                'lat' => $this->encodeLat(33.603164),
                'postal_code' => 7820005,
                'addr_city' => 39212,
                'addr_detail' => '土佐山田町逆川１４２４',
                'description' =>
                    '日本三大鍾乳洞の一つ。長い年月をかけて形成された神秘的な鍾乳石や、弥生時代の住居跡が見られる。',
                'img_ext' => 'jpg',
                'stamp_key' => $this->randKey(),
                'shows' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '牧野公園',
                'lng' => $this->encodeLng(133.289343),
                'lat' => $this->encodeLat(33.497658),
                'postal_code' => 7891201,
                'addr_city' => 39402, // 佐川町
                'addr_detail' => '甲２４５８',
                'description' =>
                    '牧野富太郎博士が自ら桜の苗木を贈ったことが始まりの公園。博士ゆかりの植物が多数植えられており、春には見事な桜が咲き誇る。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '名教館',
                'lng' => $this->encodeLng(133.288286),
                'lat' => $this->encodeLat(33.499068),
                'postal_code' => 7891201,
                'addr_city' => 39402, // 佐川町
                'addr_detail' => '甲１４７２－１',
                'description' =>
                    '牧野富太郎博士が幼少期に学んだ、佐川領主深尾氏の家塾。博士の勉学の原点ともいえる場所で、ドラマの雰囲気を感じることができる。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '金峰神社',
                'lng' => $this->encodeLng(133.286714),
                'lat' => $this->encodeLat(33.498421),
                'postal_code' => 7891201,
                'addr_city' => 39402,
                'addr_detail' => '甲１８９６',
                'description' =>
                    '朝ドラ「らんまん」の天久神社のモデル。牧野富太郎博士の生家裏山にあり、幼少期の博士がバイカオウレンに出会った大切な場所。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => 'やなせたかし朴ノ木公園',
                'lng' => $this->encodeLng(133.80308032034065),
                'lat' => $this->encodeLat(33.66135551042985),
                'postal_code' => 7814235,
                'addr_city' => 39212, // 香美市
                'addr_detail' => '香北町朴ノ木４０５',
                'description' =>
                    '柳瀬家跡地に整備された、やなせたかし氏と妻の暢（のぶ）さんが眠る墓地公園。墓碑の両側にはアンパンマンとばいきんまんの石像があり、アンパンマンミュージアムを見守るように斜めを向いているのが特徴。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => '琴ヶ浜',
                'lng' => $this->encodeLng(133.8020824006695),
                'lat' => $this->encodeLat(33.51673275537322),
                'postal_code' => 7815701,
                'addr_city' => 39307,
                'addr_detail' => '和食甲１',
                'description' =>
                    '白砂青松の美しい海岸で、日本の白砂青松100選にも選ばれている。朝ドラ「あんぱん」では「夢ヶ浜」という名で登場し、登場人物たちが並んでかき氷を食べるシーンが印象的。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5,
                'name' => 'やなせライオン公園',
                'lng' => $this->encodeLng(133.6459946355777),
                'lat' => $this->encodeLat(33.57652931775358),
                'postal_code' => 7830011,
                'addr_city' => 39204, // 南国市
                'addr_detail' => '後免町１丁目４０－１１',
                'description' =>
                    'ごめん・なはり線後免町駅のすぐ近くにある公園。朝ドラ「あんぱん」の舞台となる高知の雰囲気を色濃く残すスポット。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2,
                'name' => 'やなせたかしロード',
                'lng' => $this->encodeLng(133.64706895982113),
                'lat' => $this->encodeLat(33.57571216292037),
                'postal_code' => 7830011,
                'addr_city' => 39204, // 南国市
                'addr_detail' => '後免町２丁目１－１４',
                'description' =>
                    '後免町商店街の愛称。キャラクターの石像が通りに立ち並ぶ。朝ドラ「あんぱん」では、やなせ氏と妻・暢（のぶ）さんがモデルの登場人物たちが少年時代を過ごした町として、「御免与町（ごめんよちょう）」という場所で登場する。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 3, // 道の駅・商業施設
                'name' => '道の駅「やす」（ヤ・シィパーク）',
                'lng' => $this->encodeLng(133.75174978506766),
                'lat' => $this->encodeLat(33.53399391326713),
                'postal_code' => 7815621,
                'addr_city' => 39211, // 香南市
                'addr_detail' => '夜須町千切５３７−９０',
                'description' =>
                    '海水浴場「ヤ・シィパーク」に隣接した南国ムード漂う道の駅。特産品の販売所や飲食店が充実しており、可動橋などの観光名所へのアクセスも良好。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 2, // 港・風景
                'name' => '赤岡海浜',
                'lng' => $this->encodeLng(133.72559127169458),
                'lat' => $this->encodeLat(33.53878657183293),
                'postal_code' => 7815310,
                'addr_city' => 39211, // 香南市
                'addr_detail' => '赤岡町700',
                'description' =>
                    '「どろめ祭り」や「絵金祭り」で知られる赤岡町の海岸エリア。古い商家や蔵が残るレトロな町並みと、広大な太平洋の風景が魅力。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 3, // 直売所
                'name' => 'JA高知県直売所「とさのさと」',
                'lng' => $this->encodeLng(133.5598093271221),
                'lat' => $this->encodeLat(33.56795381845755),
                'postal_code' => 7800084,
                'addr_city' => 39201, // 高知市
                'addr_detail' => '北御座１０－４６',
                'description' =>
                    '県内最大級の売り場面積を誇る農産物直売所。高知県全域から新鮮な野菜、果物、海産物などが集結し、地元ならではの食材が手に入る。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 5, // 公園
                'name' => '宇佐しおかぜ公園',
                'lng' => $this->encodeLng(133.45284315767196),
                'lat' => $this->encodeLat(33.45010474292591),
                'postal_code' => 7811161,
                'addr_city' => 39205, // 土佐市
                'addr_detail' => '宇佐町宇佐橋田浜２７５２−７',
                'description' =>
                    '大きな親子クジラのオブジェがシンボルの海浜公園。ホエールウォッチング船の乗船場があり、潮風を感じながら散策できる憩いの場。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'plan' => 1,
                'type' => 3, // 道の駅
                'name' => '道の駅 あぐり窪川',
                'lng' => $this->encodeLng(133.14916312693188),
                'lat' => $this->encodeLat(33.23134462150663),
                'postal_code' => 7860026,
                'addr_city' => 39412, // 四万十町
                'addr_detail' => '平串２８４－１',
                'description' =>
                    '四万十川観光の玄関口に位置する道の駅。特産の生姜を使った商品や、地元ポークをふんだんに使った名物「具だくさん豚まん」が大人気。',
                'img_ext' => null,
                'stamp_key' => $this->randKey(),
                'shows' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('keywords')->insert([
            [
                'spot_id' => 1,
                'keyword' => 'パンどろぼう',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 2,
                'keyword' => 'ラスト・ソング・フォー・ユー',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 3,
                'keyword' => 'ラスト・ソング・フォー・ユー',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 3,
                'keyword' => '海がきこえる',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 4,
                'keyword' => 'The Harimaya Bridge はりまや橋',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 4,
                'keyword' => 'たいようのマキバオー',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 4,
                'keyword' => 'クッキンアイドル アイ！マイ！まいん！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 4,
                'keyword' => 'ゴリパラ見聞録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 4,
                'keyword' => '南国土佐を後にして',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 4,
                'keyword' => '海がきこえる',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 4,
                'keyword' =>
                    '特捜戦隊デカレンジャー 20th ファイヤーボール・ブースター',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 5,
                'keyword' => '所さんの学校では教えてくれないそこんトコロ！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 6,
                'keyword' => 'おへんろ。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 6,
                'keyword' => '東海オンエア',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 6,
                'keyword' => 'あんぱん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 7,
                'keyword' => '旅するSnow Man / 完全版 Travel 3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 8,
                'keyword' => '東海オンエア',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 9,
                'keyword' => 'おとぎ奉り',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 10,
                'keyword' => 'おとぎ奉り',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 11,
                'keyword' => 'おとぎ奉り',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 11,
                'keyword' => '遅咲きのヒマワリ〜ボクの人生、リニューアル〜',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 12,
                'keyword' => 'Miracle☆Summer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 12,
                'keyword' => 'ボクは好奇心のかたまり',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 12,
                'keyword' => 'ラジオアドベンチャー奇界遺産',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 13,
                'keyword' => 'らんまん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 14,
                'keyword' => '男はつらいよ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 15,
                'keyword' => '竜とそばかすの姫',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 16,
                'keyword' => '県庁おもてなし課',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 17,
                'keyword' => 'クッキンアイドル アイ！マイ！まいん！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 17,
                'keyword' => '宇宙人のあいつ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 17,
                'keyword' => '遅咲きのヒマワリ〜ボクの人生、リニューアル〜',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 18,
                'keyword' => 'ものべの',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 19,
                'keyword' => '釣りバカ日誌14 お遍路大パニック!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 20,
                'keyword' => 'ものべの',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 21,
                'keyword' => 'らんまん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 21,
                'keyword' => '宇宙人のあいつ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 22,
                'keyword' => '土佐日記',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 23,
                'keyword' => '東海オンエア',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 24,
                'keyword' => 'ものべの',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 25,
                'keyword' => '土佐日記',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 26,
                'keyword' => '夏が来たから',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 26,
                'keyword' => '釣りバカ日誌14 お遍路大パニック!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 27,
                'keyword' => 'ゴリパラ見聞録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 28,
                'keyword' => 'そふてにっ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 29,
                'keyword' => 'おへんろ。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 30,
                'keyword' => '寅さん地蔵',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 31,
                'keyword' => 'ものべの',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 32,
                'keyword' => '君が踊る、夏',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 32,
                'keyword' => '宇宙人のあいつ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 32,
                'keyword' => '竜とそばかすの姫',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 33,
                'keyword' => 'おからの華',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 34,
                'keyword' => 'あんぱん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 35,
                'keyword' => '陽暉楼',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 35,
                'keyword' => '鬼龍院花子の生涯',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 36,
                'keyword' => '旅するSnow Man / 完全版 Travel 3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 37,
                'keyword' => 'ダイハツ工業 CM「そびえ立つ道」篇',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 37,
                'keyword' => 'ピタゴラスイッチ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 37,
                'keyword' => '県庁おもてなし課',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 38,
                'keyword' =>
                    'ナゼそこ？ 1日の利用客ゼロ人!?秘境駅 山奥の行き止まりで秘境人発見',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 39,
                'keyword' =>
                    '特捜戦隊デカレンジャー 20th ファイヤーボール・ブースター',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 39,
                'keyword' => '県庁おもてなし課',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 40,
                'keyword' => 'Miracle☆Summer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 41,
                'keyword' => '美空ひばり',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 42,
                'keyword' => '釣りバカ日誌14 お遍路大パニック!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 43,
                'keyword' => 'いごっそ魂',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 43,
                'keyword' => 'クッキンアイドル アイ！マイ！まいん！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 43,
                'keyword' => 'ゴリパラ見聞録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 43,
                'keyword' => 'トラック野郎・故郷特急便',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 43,
                'keyword' => '君が踊る、夏',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 43,
                'keyword' => '悲報伝',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 43,
                'keyword' => '桂浜',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 43,
                'keyword' => '海がきこえる',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 43,
                'keyword' =>
                    '特捜戦隊デカレンジャー 20th ファイヤーボール・ブースター',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 43,
                'keyword' => '県庁おもてなし課',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 44,
                'keyword' => 'Miracle☆Summer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 45,
                'keyword' => '小春日記。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 45,
                'keyword' => '住人十色',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 45,
                'keyword' => '別冊アサ（秘）ジャーナル',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 45,
                'keyword' => '探偵!ナイトスクープ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 45,
                'keyword' => '週刊プレイボーイ 2005年9月6日号',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 45,
                'keyword' => '初恋電車',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 46,
                'keyword' => '東海オンエア',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 47,
                'keyword' => '君が踊る、夏',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 47,
                'keyword' => '県庁おもてなし課',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 47,
                'keyword' => '竜とそばかすの姫',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 48,
                'keyword' => '旅するSnow Man / 完全版 Travel 3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 49,
                'keyword' => 'ものべの',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 50,
                'keyword' => 'おへんろ。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 51,
                'keyword' => '釣りバカ日誌14 お遍路大パニック!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 52,
                'keyword' => 'おへんろ。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 53,
                'keyword' => 'CD聴こうよ。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 54,
                'keyword' => "ざつ旅-That's Journey- 第6巻",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 55,
                'keyword' => '旅するSnow Man / 完全版 Travel 3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 56,
                'keyword' => 'あしずり岬',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 56,
                'keyword' => '旅の重さ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 56,
                'keyword' => '足摺岬',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 57,
                'keyword' => '釣りバカ日誌14 お遍路大パニック!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 58,
                'keyword' => 'あんぱん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 58,
                'keyword' => 'それいけ！アンパンマン',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 59,
                'keyword' => 'ものべの',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 60,
                'keyword' => 'クッキンアイドル アイ！マイ！まいん！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 60,
                'keyword' => 'ゴリパラ見聞録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 60,
                'keyword' => '南鎌倉高校女子自転車部 第3話',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 60,
                'keyword' => '君が踊る、夏',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 60,
                'keyword' => '海がきこえる',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 60,
                'keyword' =>
                    '特捜戦隊デカレンジャー 20th ファイヤーボール・ブースター',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 61,
                'keyword' => '奇跡体験!アンビリバボー 2022年5月26日',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 61,
                'keyword' => '戦後重大事件の新事実2017〜事件発生から〇年〜',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 61,
                'keyword' => '海がきこえる',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 61,
                'keyword' =>
                    '生死を分けたその瞬間 体感！奇跡のリアルタイム 2015年3月18日',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 62,
                'keyword' => 'ボクは五才',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 62,
                'keyword' => '君が踊る、夏',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 62,
                'keyword' => '竜とそばかすの姫',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 62,
                'keyword' => '遅咲きのヒマワリ〜ボクの人生、リニューアル〜',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 63,
                'keyword' => 'おへんろ。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 63,
                'keyword' => 'らんまん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 63,
                'keyword' =>
                    '特捜戦隊デカレンジャー 20th ファイヤーボール・ブースター',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 64,
                'keyword' => '政宗くんのリベンジ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 65,
                'keyword' => '海がきこえる',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 66,
                'keyword' => 'ものべの',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 66,
                'keyword' => '東海オンエア',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 67, // スポットの順番に合わせて調整
                'keyword' => 'らんまん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 68,
                'keyword' => 'らんまん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 69,
                'keyword' => 'らんまん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 70, // やなせたかし朴ノ木公園
                'keyword' => 'あんぱん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 71, // 琴ヶ浜
                'keyword' => 'あんぱん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 72, // やなせライオン公園
                'keyword' => 'あんぱん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 73, // やなせたかしロード
                'keyword' => 'あんぱん',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 新規追加スポットへのキーワード紐付け
            [
                'spot_id' => 74, // 道の駅やす
                'keyword' => 'ザ！鉄腕！DASH！！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 75, // 赤岡漁港
                'keyword' => 'ザ！鉄腕！DASH！！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 76, // とさのさと
                'keyword' => 'ザ！鉄腕！DASH！！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 77, // 宇佐しおかぜ公園
                'keyword' => 'ザ！鉄腕！DASH！！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 78, // 道の駅あぐり窪川
                'keyword' => 'ザ！鉄腕！DASH！！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 既存スポットへのキーワード紐付け
            [
                'spot_id' => 43, // 桂浜（既存）
                'keyword' => 'ザ！鉄腕！DASH！！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 37, // 手結港可動橋（既存）
                'keyword' => 'ザ！鉄腕！DASH！！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('reviews')->insert([
            [
                'spot_id' => 2,
                'user_id' => 1,
                'rate' => 5,
                'comment' => '車窓から海が見えて最高でした！',
                'views' => 16,
                'ip_addr' => '192.0.2.11',
                'port' => 49211,
                'user_agent' =>
                    'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Mobile Safari/537.36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 2,
                'user_id' => 4,
                'rate' => 3,
                'comment' =>
                    '前は往復で移動するだけで簡単にフリーきっぷの元が取れたけど、流石に値上げされたか……',
                'views' => 8,
                'ip_addr' => '192.0.2.12',
                'port' => 49212,
                'user_agent' =>
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:146.0) Gecko/20100101 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 66,
                'user_id' => 2,
                'rate' => 4,
                'comment' =>
                    '思ってたより長いし、広い空間も多くて迫力あって良かった！',
                'views' => 18,
                'ip_addr' => '192.0.2.13',
                'port' => 49213,
                'user_agent' =>
                    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:146.0) Gecko/20100101 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('coupons')->insert([
            [
                'spot_id' => 4,
                'name' => 'はりまや橋通行料 50% OFF',
                'cond_spot_id' => 2,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 12,
                'name' => 'UFO発見確率 1% UP',
                'cond_spot_id' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 37,
                'name' => '手結港可動橋観覧料 50% OFF',
                'cond_spot_id' => null,
                'expires_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('user_coupons')->insert([
            [
                'coupon_id' => 1,
                'user_id' => 2,
                'key' => $this->randKey(),
                'is_used' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'coupon_id' => 1,
                'user_id' => 5,
                'key' => $this->randKey(),
                'is_used' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('stamps')->insert([
            [
                'spot_id' => 2,
                'user_id' => 2,
                'ip_addr' => '192.0.2.21',
                'port' => 49221,
                'user_agent' =>
                    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:146.0) Gecko/20100101 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 2,
                'user_id' => 5,
                'ip_addr' => '192.0.2.22',
                'port' => 49222,
                'user_agent' =>
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 Edg/143.0.0.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 24,
                'user_id' => 4,
                'ip_addr' => '192.0.2.23',
                'port' => 49223,
                'user_agent' =>
                    'Mozilla/5.0 (Android 15; Mobile; rv:146.0) Gecko/146.0 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'spot_id' => 66,
                'user_id' => 5,
                'ip_addr' => '192.0.2.24',
                'port' => 49224,
                'user_agent' =>
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 Edg/143.0.0.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('queries')->insert([
            [
                'user_id' => 2,
                'query' => 'この間にある観光スポットを推薦して',
                'from_spot_id' => 2,
                'to_spot_id' => 6,
                'ip_addr' => '192.0.2.31',
                'port' => 49231,
                'user_agent' =>
                    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:146.0) Gecko/20100101 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'query' => 'この付近で「ものべの」の聖地はどこ？',
                'from_spot_id' => 24,
                'to_spot_id' => null,
                'ip_addr' => '192.0.2.32',
                'port' => 49232,
                'user_agent' =>
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:146.0) Gecko/20100101 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('photos')->insert([
            [
                'user_id' => 4,
                'lng' => $this->encodeLng(133.685047),
                'lat' => $this->encodeLat(33.607133),
                'img_ext' => 'jpg',
                'comment' =>
                    'ついに香美市に到着！あのゲームにも出てきた場所、土佐山田駅だ！',
                'ip_addr' => '192.0.2.41',
                'port' => 49241,
                'user_agent' =>
                    'Mozilla/5.0 (Android 15; Mobile; rv:146.0) Gecko/146.0 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('api_keys')->insert([
            [
                'user_id' => 3,
                'name' => 'テスト用',
                'key' => hash(
                    'sha3-512',
                    'R9AnJFbw34/CWEQhwBVzDC4BGiAfM6IigWoU5pKm9L7y3zh6mzKEB32KjcyhPdq.d6hNo6+Iykh0EOVHQ/Wyp',
                    true,
                ),
                'ip_addr' => '192.0.2.51',
                'port' => 49251,
                'user_agent' =>
                    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:146.0) Gecko/20100101 Firefox/146.0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        File::copyDirectory(__DIR__ . '/files', storage_path('app/public'));
    }
    private function randKey()
    {
        return rand(0, PHP_INT_MAX);
    }
}
